#
# Module manifest for module 'garuda'
#
# Generated by: jokourno
#
# Generated on: 15/6/2026
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '4bf85569-7bfb-43fa-9467-80828b5af066'

# Author of this module
Author = 'Joko Purnomo'


# Copyright statement for this module
Copyright = '(c) Joko Purnomo. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'PowerShell-based, multithreaded platform for probing remote hosts'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = '7.6.3'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @(Discovery, Scanner)

        # A URL to the license for this module.
        # LicenseUri = 'https://github.com/jokourno12/garuda?tab=MIT-1-ov-file'

        # A URL to the main website for this project.
        # ProjectUri = 'https://github.com/jokourno12/garuda'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

    } # End of PSData hashtable

} # End of PrivateData hashtable

}